import { Project, TeamMember, StatItem } from './types';
import { Images } from '@/assets/images';

export const NAV_LINKS = [
  { name: 'Home', href: '#home' },
  { name: 'Games', href: '#games' },
  { name: 'About', href: '#about' },
  { name: 'Team', href: '#team' },
];

export const STATS: StatItem[] = [
  { value: '1M+', label: 'Visits' },
  { value: '3', label: 'Games' },
  { value: '100K+', label: 'Likes' },
  { value: '50K+', label: 'Members' },
];

export const PROJECTS: Project[] = [
  {
    id: 'mosque',
    title: 'Mosque [Eid Mubarak 1447 H]',
    description: 'Explore a beautifully crafted mosque, learn about Islamic architecture, and celebrate Eid with friends in this immersive experience.',
    imageUrl: Images.mosque,
    visits: '1.2M',
    likes: '45K',
    favs: '12K',
    status: 'Full Release',
    badge: { text: 'BEST', colorClass: 'bg-yellow-500 text-black shadow-yellow-500/20' },
    statusColorClass: 'text-primary bg-primary/10 border-primary/20',
    playUrl: 'https://www.roblox.com/games/7129422087/Mosque',
  },
  {
    id: 'leaked-items',
    title: 'Leaked Items',
    description: 'Discover the latest leaked Roblox items before anyone else! Stay ahead of the trends with our up-to-date database of upcoming releases.',
    imageUrl: Images.leakedItems,
    visits: '850K',
    likes: '28K',
    favs: '9.5K',
    status: 'Beta',
    badge: { text: 'UPDATED', colorClass: 'bg-primary text-white shadow-primary/20' },
    statusColorClass: 'text-yellow-500 bg-yellow-500/10 border-yellow-500/20',
    playUrl: 'https://www.roblox.com/games/8032278067/Leaked-Items',
  },
  {
    id: 'talk-to-david',
    title: 'Talk to David',
    description: 'Provides INFORMATION about the HISTORY, EVOLUTION, and FACTS regarding ROBLOX from 2006 - 2023. 🕛 In this EXPERIENCE you can play side gameplay like FIGHTING in the CROSSROAD ARENA with OLD WEAPONS. ⚔',
    imageUrl: Images.talkToDavid,
    visits: '320K',
    likes: '8K',
    favs: '3K',
    status: 'Alpha',
    badge: { text: 'NEW', colorClass: 'bg-green-500 text-white shadow-green-500/20' },
    statusColorClass: 'text-orange-400 bg-orange-400/10 border-orange-400/20',
    playUrl: 'https://www.roblox.com/games/7189744178/Talk-to-David',
  },
  {
    id: 'honeycomb-mazes',
    title: '100 Floors Honeycomb Mazes',
    description: 'Can you escape the honeycomb maze? Explore 100 floors of challenging mazes filled with twists, turns, and sweet surprises at every corner!',
    imageUrl: Images.underDevelopment,
    visits: '15K',
    likes: '1.5K',
    favs: '500',
    status: 'In Development',
    badge: { text: 'PRE-ALPHA', colorClass: 'bg-purple-500 text-white shadow-purple-500/20' },
    statusColorClass: 'text-purple-500 bg-purple-500/10 border-purple-500/20',
    playUrl: 'https://www.roblox.com/share/g/32462874',
  },
  {
    id: 'heaven-or-hell',
    title: 'Heaven or Hell',
    description: 'Nah, can you reach HEAVEN or fall into HELL. Did you know there is life after death in the world.',
    imageUrl: Images.heavenOrHell,
    visits: '850K',
    likes: '28K',
    favs: '9.5K',
    status: 'Beta',
    badge: { text: 'UPDATED', colorClass: 'bg-primary text-white shadow-primary/20' },
    statusColorClass: 'text-yellow-500 bg-yellow-500/10 border-yellow-500/20',
    playUrl: 'https://www.roblox.com/games/13025811313/Heaven-or-Hell',
  },
  {
    id: 'box-brawlers',
    title: 'Box Brawlers',
    description: 'A ROBLOX EXPERIENCE that offers MULTIPLAYER MELEE BATTLES with WEAPON surprise BOXES. In this game you will join the BATTLE againts other players in ARENA provided 📦. FIGHT freely with WEAPONS that can be found around the MAP, defeat ENEMIES and become the KING of the CITY of STREETS!',
    imageUrl: Images.boxBrawlers,
    visits: '850K',
    likes: '28K',
    favs: '9.5K',
    status: 'Beta',
    badge: { text: 'UPDATED', colorClass: 'bg-primary text-white shadow-primary/20' },
    statusColorClass: 'text-yellow-500 bg-yellow-500/10 border-yellow-500/20',
    playUrl: 'https://www.roblox.com/games/13254707543/Box-Brawlers',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'dedek_cules',
    name: 'dedek_cules',
    role: 'Lead Developer',
    description: 'Scripter, Builder, UI/UX.',
    imageUrl: Images.decul,
    profileLink: 'https://www.roblox.com/id/users/2253933194/profile',
  },
  {
    id: 'dedek_madrid',
    name: 'dedek_madrid',
    role: 'Co-lead Developer',
    description: '3D Modeling, Texturing, Admin.',
    imageUrl: Images.demit,
    profileLink: 'https://www.roblox.com/id/users/2681062449/profile',
  },
];